# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My personal website - Vincent von Appen
author:
  name: Vincent von Appen
  email: your-email@domain.com
description: >- # this means to ignore newlines until next key value
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: false # set to true to show excerpts on the homepage


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vinvapp.github.io" # the base hostname & protocol for your site, e.g. http://example.com


################################################################
#                      Picture blog 
################################################################

#title: My personal blog - Adam Neilson
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#permalink: ':title/'
#baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Vincent # add your name
author-pic: vincent-face-1.jpg
about-author: >- # this means to ignore newlines until next key value
  My name is Vincent von Appen. I’m a student at TUM (currently 
  taking a vacation semester) and travel enthusiasts who wants to 
  share some of his stories.
author-pic-professional: vincent-face-2.jpg

# Contact links
email: # Add your Email address
website: vinvapp.github.io/ # Add your website, do not add http://
linkedin: falk-vincent-von-appen # Add your Linkedin handle
github: vinvapp # Add your Github handle
facebook: vincent.vonapp # Add your Facebook handle
instagram: vincentvonappen # Add your Instagram handle
#phone: # Add your Phone number
#twitter: '@artemsheludko_' # Add your Twitter handle
#pinterest: # Add your Pinterest handle

# Newsletter
#mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
#analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: "/blog/page:num/"

#paginate_multiple:
#  - paginate: 6
#    paginate_path: '/blog/page:num/'
#    sub_dir: '/blog/'
#  - paginate: 6
#    paginate_path: '/recipes/page:num/'
#    sub_dir: '/recipes/'

# Build settings
markdown: kramdown


plugins:
  - jekyll-paginate
  - jekyll-paginate-multiple
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

include: [_pages]
exclude: [
  "node_modules", 
  "gulpfile.js", 
  "package.json", 
  "yarn.lock", 
  "package-lock.json", 
  "assets/css/sass/",
  "tags_list", 
  "makefile"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

include: 
  - _pages
  - _posts/blog/
  - _posts/recipes/
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - yarn.lock
  - _sass/
  - _archive/
  - makefile
  - tags_list
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/